# Generated by Django 4.2.4 on 2023-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_code_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
